-- Client-only buff labels. Keys are gameplay IDs and must stay unchanged.
return {
    add_health = { name = "+󰀍", desc = "Restores 1 health per second." },
    buff_10s_1_health = { name = "+󰀍", desc = "Restores 1 health per second." },
    add_hunger = { name = "+󰀎", desc = "Restores 1 hunger per second." },
    add_sanity = { name = "+󰀓", desc = "Restores 1 sanity per second." },
    poison = { name = "Poison", desc = "Loses 1 health every 3 seconds." },
    monster_poison = { name = "Poison (monster)", desc = "Loses 5 health every 2 seconds." },
    reduce_speed = { name = "Slowed", desc = "Movement speed reduced by 40%." },
    player_healthSuppressNum = { name = "Healing suppression", desc = "Healing reduced by 90%." },
    monster_healthSuppressNum = { name = "Healing suppression", desc = "Healing reduced by 90%." },
    monster_add_target_damage = { name = "Fear", desc = "Loses 1 sanity per second." },
    turret_fire = { name = "Burning", desc = "Takes 1 fire damage per second." },
    turret_poison = { name = "Bleeding", desc = "Takes 1 damage every 0.5 seconds." },
    suit_basalt = { name = "Basalt Power", desc = "Basalt set effect." , icon = "Set\nEffect" },
    suit_basalt_cd = { name = "Basalt set cooldown", desc = "Set effect on cooldown.", icon = "On\nCooldown" },
    suit_yhby = { name = "Divine Blessing", desc = "Immune to healing suppression, poison and wetness.\nGrants nearby healing when hit.", icon = "Set\nEffect" },
    suit_yhby_cd = { name = "Blessing cooldown", desc = "Set effect on cooldown.", icon = "On\nCooldown" },
    add_cold = { name = "Cold vulnerability", desc = "Temperature falls by 5 degrees each second." },
    add_hot = { name = "Heat vulnerability", desc = "Temperature rises by 5 degrees each second." },
    add_armor_consume = { name = "Fragile Armor", desc = "Armor loses twice as much durability when hit." },
    hh_beetle_pig_speed = { name = "Speed Boost", desc = "Movement speed increased." },
    test_01 = { name = "Test 01", desc = "Test 01" },
    test_02 = { name = "Test 02", desc = "Test 02" },
    test_03 = { name = "Test 03", desc = "Test 03" },
    test_04 = { name = "Test 04", desc = "Test 04" },
    test_05 = { name = "Test 05", desc = "Test 05" },
    test_06 = { name = "Test 06", desc = "Test 06" },
    test_07 = { name = "Test 07", desc = "Test 07" },
    test_08 = { name = "Test 08", desc = "Test 08" },
    test_09 = { name = "Test 09", desc = "Test 09" },
    test_10 = { name = "Test 10", desc = "Test 10" },
}
