-- English labels and formats for the client-rendered hover panel.
local gems = {
    durableGem = "Restores 1 durability every 2 seconds.",
    damageBoostGem = "Adds 10 damage.",
    powerMettleStone = "Increases damage by 3 percent.",
    strideBead = "Increases movement speed by 3 percent.",
    shadowNightBead = "Adds 20 damage at night.",
    twilightBead = "Adds 20 damage at dusk.",
    dayShineBead = "Adds 20 damage during the day.",
    critStrikeStone = "Adds 3 percent critical chance and 10 percent critical damage.",
    resistDamageGem = "Reduces incoming damage by 3.",
    retaliateGem = "Reflects 3 damage when hit.",
    spiderVengeance = "Adds 20 damage against spiders.",
    insectStrikeCrystal = "Adds 20 damage against insects.",
    shadowStrikeLuminary = "Adds 20 damage against shadow creatures.",
    bossStrikeGem = "Adds 50 damage against bosses.",
    followCritical = "Adds 3 percent follower critical chance.",
    followDamage = "Adds 10 follower damage.",
    followArmor = "Reduces damage taken by followers by 3.",
    treasure_armor = "Treasure: restores durability rapidly.",
    treasure_atk = "Treasure: adds 50 damage.",
    treasure_bj = "Treasure: adds 20 percent critical chance.",
    elementBead = "Special: immune to negative effects.",
    eightPigGem = "Yin Yin Stone: immune to reflected damage and negative effects.",
    nkGem = "Jiaxin's Blessing (exclusive).",
    baconOmeletteBlessArmor = "Supreme defense: immunity, 1000 durability and rapid durability regen.",
    baconOmeletteBlessAtk = "Special attack: 50 damage, 15 percent damage bonus and 5 percent movement speed.",
    baconOmeletteBlessCritical = "Special critical: 10 percent critical chance and 50 percent critical damage.",
    baconOmeletteTrueDamage = "Supreme true damage: adds 100 true damage on hit.",
    fxGem = "Special: plays a text effect.",
}

local monster_formats = {
    addMaxHealthNum = "Increases maximum health by %s.",
    addMaxHealthPercent = "Increases maximum health by %s percent.",
    addComDamageNum = "Increases damage by %s.",
    addComDamagePercent = "Increases damage by %s percent.",
    atkAddPoison = "Attacks have a %s percent chance to poison the target.",
    hitAddPoison = "Attackers have a %s percent chance to be poisoned.",
    atkChanceAddFreeze = "Attacks have a %s percent chance to freeze the target for 2 seconds.",
    hitChanceAddFreeze = "Attackers have a %s percent chance to be frozen for 2 seconds.",
    atkChanceReduceSpeed = "Has a %s percent chance to slow the target on hit.",
    hitChanceReduceSpeed = "Attackers have a %s percent chance to be slowed.",
    addSpeedPercent = "Increases movement speed by %s percent.",
    atkBlood = "Adds %s percent lifesteal.",
    addCriticalHitRate = "Adds %s percent critical chance and 50 percent critical damage.",
    bossAddCriticalHitRate = "Adds %s percent critical chance and 120 percent critical damage.",
    addReduceAttackedDamage = "Reduces incoming damage by %s.",
    addReboundDamageNum = "Reflects %s damage.",
    addDayDamage = "Adds %s damage during the day.",
    addDuskDamage = "Adds %s damage at dusk.",
    addNightDamage = "Adds %s damage at night.",
    addSuppressAddHealth = "Attacks have a %s percent chance to reduce target healing by 90 percent.",
    hitSuppressAddHealth = "Attackers have a %s percent chance to receive 90 percent less healing.",
    reboundDamagePercent = "Reflects %s percent damage.",
    deadAddFreeze = "On death, adds one freeze stack within four tiles.",
    deadAddMoisture = "On death, adds 10 wetness within four tiles.",
    deadAddExplode = "On death, explodes for 30 damage within four tiles.",
    deadAddPoison = "On death, poisons targets within four tiles.",
    deadAddReduceSpeed = "On death, slows targets within four tiles.",
    iceTurret = "Passive skill: Ice Turret.",
    fireTurret = "Passive skill: Fire Turret.",
    poisonTurret = "Passive skill: Poison Turret.",
    iceLaser = "Attack skill: Laser.",
    addHealth3sNum = "Restores %s health every 3 seconds.",
    addHealth5sNum = "Restores %s health every 5 seconds.",
    addHealth10sNum = "Restores %s health every 10 seconds.",
    addHealth3sPercent = "Restores %s percent health every 3 seconds.",
    addTargetDamage = "Has a %s percent chance to lower target sanity for 30 seconds.",
    immuneFreeze = "Immune to freezing.",
    noHitDamage = "Has a %s percent chance to block incoming damage.",
    hitAddMoisture = "Attackers have a %s percent chance to gain 20 wetness.",
    addHealthPercent03 = "Restores %s percent health every 3 seconds.",
    addHealthPercent05 = "Restores %s percent health every 5 seconds.",
    addHealthPercent10 = "Restores %s percent health every 10 seconds.",
    hitAddCold = "Attackers have a %s percent chance to become more vulnerable to cold for 30 seconds.",
    hitAddHot = "Attackers have a %s percent chance to become more vulnerable to heat for 30 seconds.",
    reduceNightDamage = "Reduces damage taken at night by %s.",
    reduceSunlightDamage = "Reduces damage taken during the day by %s.",
    reduceAfterglowDamage = "Reduces damage taken at dusk by %s.",
    atkReduceArmor = "Attacks have a %s percent chance to weaken target armor.",
    reducePercentDamage = "Reduces incoming damage by %s percent.",
    immuneTearing = "Immune to rending.",
}
local player_formats = {
    criticalHitRate = "Critical chance +%s%%",
    criticalHitEffect = "Critical damage +%s%%",
    addComDamage = "Flat damage +%s",
    addComDamagePercent = "Damage bonus +%s%%",
    reduceAttackedDamage = "Flat damage reduction +%s",
    trueDamageNum = "True damage +%s",
    addSpeedPercent = "Movement speed +%s%%",
}

local food_types = {
    GENERIC = "General",
    MEAT = "Meat",
    VEGGIE = "Vegetable",
    ELEMENTAL = "Elemental",
    GEARS = "Clockwork",
    HORRIBLE = "Nightmare",
    INSECT = "Insect",
    SEEDS = "Seed",
    BERRY = "Berry",
    RAW = "Raw",
    BURNT = "Burnt",
    ROUGHAGE = "Roughage",
    WOOD = "Wood",
    GOODIES = "Treat",
    MONSTER = "Monster",
    NIL = "Unknown",
}
local food_tags = {
    veggie = "Vegetable",
    fruit = "Fruit",
    monster = "Monster",
    sweetener = "Sweetener",
    meat = "Meat",
    fish = "Fish",
    magic = "Magic",
    egg = "Egg",
    decoration = "Butterfly",
    dairy = "Dairy",
    fat = "Fat",
    inedible = "Twig",
    frozen = "Ice",
    seed = "Seed",
    fungus = "Fungus",
    mushrooms = "Mushroom",
    poultry = "Poultry",
    wings = "Wings",
    seafood = "Seafood",
    nut = "Nut",
    cactus = "Cactus",
    starch = "Starch",
    grapes = "Grapes",
    citrus = "Citrus",
    tuber = "Tuber",
    shellfish = "Shellfish",
    rawmilk = "Milk",
    bulb = "Light Bulb",
    spices = "Spice",
    challa = "Challah",
    flour = "Flour",
    cacao_cooked = "Cocoa",
}
local tool_types = {
    CHOP = "Chop",
    DIG = "Dig",
    HAMMER = "Hammer",
    MINE = "Mine",
    NET = "Catch",
    PLAY = "Play",
    UNSADDLE = "Unsaddle",
    REACH_HIGH = "Reach",
}

return {
    food_types = food_types,
    food_tags = food_tags,
    tool_types = tool_types,
    monster_formats = monster_formats,
    player_formats = player_formats,
    gems = gems,
    hh_01_name = { name = "", format = "%s" },
    hh_01_guid = { name = "GUID:", format = "%s" },
    hh_01_text = { name = "Description:", format = "%s" },
    hh_02_boss_equip = { name = "Stars:", format = "%s" },
    hh_02_health = { name = "Health:", format = "%s/%s damage reduction %s%%" },
    hh_02_hunger = { name = "Hunger:", format = "%s/%s" },
    hh_03_combat = { name = "Damage:", format = "%s range: %s multiplier: %s" },
    hh_03_weapon = { name = "Weapon:", format = "%s range: %s" },
    hh_04_edible = { name = "Food:", format = "%s hunger: %s sanity: %s health: %s" },
    hh_05_food_tag = { name = "Food tags:", format = "%s" },
    hh_06_armor = { name = "Armor:", format = "%s" },
    hh_07_finiteuses = { name = "Durability:", format = "%s/%s" },
    hh_08_fueled = { name = "Fuel:", format = "%s/%s" },
    hh_09_tool = { name = "Tool:", format = "%s" },
    hh_10_stackable = { name = "Stack:", format = "%s/%s" },
    hh_11_naughty_value = { name = "Naughtiness:", format = "%s" },
    hh_12_container = { name = "Container:", format = "%s/%s%s" },
    hh_13_perishable = { name = "Spoils in:", format = "%s days" },
    hh_14_unwrappable = { name = "Bundle:", format = "%s" },
    hh_15_stewer = { name = "Cooking:", format = "%s; %s seconds left" },
    hh_16_growable = { name = "Stage:", format = "%s; next stage in %s days" },
    hh_17_pickable = { name = "Ready in:", format = "%s days" },
    hh_18_insulator = { name = "Insulation:", format = "%s" },
    hh_20_fishable = { name = "Fish left:", format = "%s" },
    hh_21_follower = { name = "Leader:", format = "%s; %s seconds left" },
    hh_23_equippable = { name = "Move speed:", format = "%s%%" },
    hh_24_tradable = { name = "Trade value:", format = "Gold: +%s, stone: +%s" },
    hh_26_childspawner = { name = "Creatures:", format = "%s/%s" },
    hh_27_domesticatable = { name = "Domestication:", format = "%s" },
    hh_28_dryer = { name = "Drying:", format = "%s" },
    hh_29_farmplantstress = { name = "Crop:", format = "%s stress points" },
    hh_30_cookable = { name = "Roasts into:", format = "%s" },
    hh_31_locomotor = { name = "Move speed:", format = "Run: %s walk: %s" },
    hh_31_hh_tag = { name = "Special tags:", format = "%s" },
    hh_32_hh_gem = { name = "Gems:", format = "%s" },
    hh_32_hh_gem_check = { name = "Requirements:", format = "%s" },
    hh_32_hh_equip = { name = "Affixes:", format = "%s" },
    hh_32_hh_equip_star = { name = "Stars:", format = "%s" },
    hh_32_hh_equip_suit = { name = "Set:", format = "%s" },
    hh_32_hh_monster = { name = "Enhanced:", format = "%s" },
    hh_33_hh_follow = { name = "Follower bonus:", format = "%s" },
    hh_32_hh_save = { name = "Owner:", format = "%s-%s" },
    hh_32_hh_player = { name = "Stats:", format = "%s" },
    hh_33_hh_level = { name = "Level:", format = "%s" },
    hh_34_boss_equip = { name = "Bound to:", format = "%s" },
    hh_99_special_01 = { name = "Special:", format = "%s" },
    hh_99_special_02 = { name = "Special:", format = "%s" },
    hh_99_special_03 = { name = "Special:", format = "%s" },
    hh_99_special_04 = { name = "Special:", format = "%s" },
    hh_99_painter = { name = "Artist:", format = "%s" },
    hh_99_prefab = { name = "Prefab:", format = "%s" },
    hh_99_idle = { name = "Animation:", format = "%s %s %s" },
    hh_99_path = { name = "Path:", format = "%s" },
    hh_99_exception = { name = "Error:", format = "%s" },
}
