-- English labels and formats for the client-rendered hover panel.
local gems = {
    durableGem = "Restores 1 durability every 2 seconds.",
    damageBoostGem = "Adds 10 damage.",
    powerMettleStone = "Increases damage by 3 percent.",
    strideBead = "Increases movement speed by 3 percent.",
    shadowNightBead = "Adds 20 damage at night.",
    twilightBead = "Adds 20 damage at dusk.",
    dayShineBead = "Adds 20 damage during the day.",
    critStrikeStone = "Adds 3 percent critical chance and 10 percent critical damage.",
    resistDamageGem = "Reduces incoming damage by 3.",
    retaliateGem = "Reflects 3 damage when hit.",
    spiderVengeance = "Adds 20 damage against spiders.",
    insectStrikeCrystal = "Adds 20 damage against insects.",
    shadowStrikeLuminary = "Adds 20 damage against shadow creatures.",
    bossStrikeGem = "Adds 50 damage against bosses.",
    followCritical = "Adds 3 percent follower critical chance.",
    followDamage = "Adds 10 follower damage.",
    followArmor = "Reduces damage taken by followers by 3.",
    treasure_armor = "Treasure: restores durability rapidly.",
    treasure_atk = "Treasure: adds 50 damage.",
    treasure_bj = "Treasure: adds 20 percent critical chance.",
    elementBead = "Special: immune to negative effects.",
    eightPigGem = "Yin Yin Stone: immune to reflected damage and negative effects.",
    nkGem = "Jiaxin's Blessing (exclusive).",
    baconOmeletteBlessArmor = "Supreme defense: immunity, 1000 durability and rapid durability regen.",
    baconOmeletteBlessAtk = "Special attack: 50 damage, 15 percent damage bonus and 5 percent movement speed.",
    baconOmeletteBlessCritical = "Special critical: 10 percent critical chance and 50 percent critical damage.",
    baconOmeletteTrueDamage = "Supreme true damage: adds 100 true damage on hit.",
    fxGem = "Special: plays a text effect.",
}

return {
    gems = gems,
    hh_01_name = { name = "", format = "%s" },
    hh_01_guid = { name = "GUID:", format = "%s" },
    hh_01_text = { name = "Description:", format = "%s" },
    hh_02_boss_equip = { name = "Stars:", format = "%s" },
    hh_02_health = { name = "Health:", format = "%s/%s damage reduction %s%%" },
    hh_02_hunger = { name = "Hunger:", format = "%s/%s" },
    hh_03_combat = { name = "Damage:", format = "%s range: %s multiplier: %s" },
    hh_03_weapon = { name = "Weapon:", format = "%s range: %s" },
    hh_04_edible = { name = "Food:", format = "%s hunger: %s sanity: %s health: %s" },
    hh_05_food_tag = { name = "Food tags:", format = "%s" },
    hh_06_armor = { name = "Armor:", format = "%s" },
    hh_07_finiteuses = { name = "Durability:", format = "%s/%s" },
    hh_08_fueled = { name = "Fuel:", format = "%s/%s" },
    hh_09_tool = { name = "Tool:", format = "%s" },
    hh_10_stackable = { name = "Stack:", format = "%s/%s" },
    hh_11_naughty_value = { name = "Naughtiness:", format = "%s" },
    hh_12_container = { name = "Container:", format = "%s/%s%s" },
    hh_13_perishable = { name = "Spoils in:", format = "%s days" },
    hh_14_unwrappable = { name = "Bundle:", format = "%s" },
    hh_15_stewer = { name = "Cooking:", format = "%s; %s seconds left" },
    hh_16_growable = { name = "Stage:", format = "%s; next stage in %s days" },
    hh_17_pickable = { name = "Ready in:", format = "%s days" },
    hh_18_insulator = { name = "Insulation:", format = "%s" },
    hh_20_fishable = { name = "Fish left:", format = "%s" },
    hh_21_follower = { name = "Leader:", format = "%s; %s seconds left" },
    hh_23_equippable = { name = "Move speed:", format = "%s%%" },
    hh_24_tradable = { name = "Trade value:", format = "Gold: +%s, stone: +%s" },
    hh_26_childspawner = { name = "Creatures:", format = "%s/%s" },
    hh_27_domesticatable = { name = "Domestication:", format = "%s" },
    hh_28_dryer = { name = "Drying:", format = "%s" },
    hh_29_farmplantstress = { name = "Crop:", format = "%s stress points" },
    hh_30_cookable = { name = "Roasts into:", format = "%s" },
    hh_31_locomotor = { name = "Move speed:", format = "Run: %s walk: %s" },
    hh_31_hh_tag = { name = "Special tags:", format = "%s" },
    hh_32_hh_gem = { name = "Gems:", format = "%s" },
    hh_32_hh_gem_check = { name = "Requirements:", format = "%s" },
    hh_32_hh_equip = { name = "Affixes:", format = "%s" },
    hh_32_hh_equip_star = { name = "Stars:", format = "%s" },
    hh_32_hh_equip_suit = { name = "Set:", format = "%s" },
    hh_32_hh_monster = { name = "Enhanced:", format = "%s" },
    hh_33_hh_follow = { name = "Follower bonus:", format = "%s" },
    hh_32_hh_save = { name = "Owner:", format = "%s-%s" },
    hh_32_hh_player = { name = "Stats:", format = "%s" },
    hh_33_hh_level = { name = "Level:", format = "%s" },
    hh_34_boss_equip = { name = "Bound to:", format = "%s" },
    hh_99_special_01 = { name = "Special:", format = "%s" },
    hh_99_special_02 = { name = "Special:", format = "%s" },
    hh_99_special_03 = { name = "Special:", format = "%s" },
    hh_99_special_04 = { name = "Special:", format = "%s" },
    hh_99_painter = { name = "Artist:", format = "%s" },
    hh_99_prefab = { name = "Prefab:", format = "%s" },
    hh_99_idle = { name = "Animation:", format = "%s %s %s" },
    hh_99_path = { name = "Path:", format = "%s" },
    hh_99_exception = { name = "Error:", format = "%s" },
}
