-- English text is added section by section. Missing entries fall back to Chinese.
return {
    forge = {
        draw = "Draw", inherit = "Inherit", enhance = "Enhance",
        selective_clear = "<Select affixes to remove>",
        clear_help = "Choose the affixes you want to remove.",
        clear_cost = "Cost: Cleansing Tokens (see Gems tab)",
        clear_quantity = "One token per selected affix.",
        clear = "Remove",
    },
    equip_ui = {
        title = "Equipment Forge", put_in = "Add all", dismantle = "Dismantle all",
        equip = "↑\nGear", enchant_item = "↑\nEnchant",
        cleansing_item = "↑\nCleanse",
        upgrade = "Upgrade", enchant = "Enchant", clear = "Remove",
        enchant_hint = "[Stone / Scroll]\nAdd a random or selected affix",
        reroll_hint = "[Reset Gem]\nReroll affix values",
        clear_hint = "[Cleansing Stone]\nRemove one random affix",
        gem_title = "Socket Gems",
        inventory_hint = "↓ Your items ↓",
        equipment_hint = "Equipment →", gem = "Gem",
        confirm = "Confirm", cancel = "Cancel",
    },
    items = {
        a_punchStone = "Socket Stone",
        a_stoneDecoder = "Gem Remover",
        a_refreshStone = "Reset Gem",
        durableGem = "Durability Gem",
        damageBoostGem = "Damage Gem",
        powerMettleStone = "Power Stone",
        strideBead = "Speed Bead",
        shadowNightBead = "Nightfall Bead",
        followCritical = "Follower Critical Gem",
        followDamage = "Follower Damage Gem",
        followArmor = "Follower Defense Gem",
        twilightBead = "Dusk Bead",
        dayShineBead = "Daylight Bead",
        critStrikeStone = "Critical Stone",
        resistDamageGem = "Defense Stone",
        vigorousStone = "Vigor Stone",
        frostGuardCrystal = "Frostguard Crystal",
        heatGuardCrystal = "Heatguard Crystal",
        elementBead = "Elemental Star",
        retaliateGem = "Thorns Gem",
        spiderVengeance = "Spider Strike Gem",
        insectStrikeCrystal = "Insect Strike Crystal",
        shadowStrikeLuminary = "Shadow Strike Gem",
        bossStrikeGem = "Boss Strike Gem",
        z_clean_stone = "Cleansing Token",
        eightPigGem = "Yin Yin Stone",
        nkGem = "Jiaxin Candy",
        baconOmeletteBlessArmor = "Ultimate Defense Gem",
        baconOmeletteBlessAtk = "Ultimate Attack Gem",
        baconOmeletteBlessCritical = "Ultimate Critical Gem",
        baconOmeletteTrueDamage = "True Damage Gem",
        fxGem = "Effect Gem",
        treasure_atk = "Treasure Attack Gem",
        treasure_bj = "Treasure Critical Gem",
        treasure_armor = "Treasure Durability Gem",
        z_fertilizer = "Spell: Fertilize",
        z_plant = "Spell: Grow",
        z_soil = "Spell: Till Soil",
        z_rain = "Spell: Rain",
        z_sleep = "Spell: Sleep",
        z_stone = "Spell: Petrify",
    },
    mod_help = {
        "#Gameplay:orange:30",
        "#1. Creatures may spawn with random affixes; their maximum health rises over time.:white:25",
        "#2. Defeating enhanced creatures may drop equipment with special affixes.:white:25",
        "#3. Dismantling affixed equipment has a 10% chance to yield an affix stone (guaranteed with 3+ affixes).:white:25",
        "#4. Elite and boss creatures may drop equipment bundles or rare affix stones.:white:25",
        "#5. Defeating creatures may grant :white:25@effect_tally::25:25# or :white:25@remove_stone::25:25",
        "#6. Defeating creatures may grant special gems (see the forge's Gem tab).:white:25",
        "#7. Craft :white:25@suit_build::25:25# to inherit affixes and remove selected affixes.:white:25",
        "#8. Upgrade in :white:25@suit_build::25:25# to reroll affix values using a reset gem.:white:25",
        "# :white:50",

        "#Items:orange:30",
        "@effect_tally::25:25# Randomly enchants one piece of equipment at the forge.:white:25",
        "@remove_stone::25:25# Removes a random equipment affix at the forge.:white:25",
        "@essence::25:25# General crafting material.:white:25",
        "@cat_box::25:25# Portable enchantment box; converts affix stones into essence.:white:25",
        "@duck_box::25:25# Portable Pig King container.:white:25",
        "@staff_dis::25:25# Dismantles equipment or converts affix stones into essence.:white:25",
        "@ice_knife::25:25# Attacks can send out three waves of area fire damage.:white:25",
        "@staff_star::25:25# Ranged weapon with three projectiles.:white:25",
        "@treasure_tally::25:25# Reveals treasure locations.:white:25",
        "@treasure_build::25:25# Treasure site with encounters and enhanced creatures.:white:25",
        "@egg_nest::25:25# Egg incubator and display stand.:white:25",
        "#Common eggs - normal creatures.:white:25@egg_common::25:25",
        "#Precious eggs - elite creatures.:white:25@egg_silver::25:25",
        "#Rare eggs - bosses.:white:25@egg_gold::25:25",
        "#Starry eggs - treasure.:white:25@egg_starry_sky::25:25",
        "#Black eggs - extraordinary luck.:white:25@egg_black::25:25",
        "@hat_star::25:25# Upgradeable crown, sometimes found through hatching.:white:25",
        "# :white:50",

        "#Creature difficulty:orange:30",
        "#Easy - 1 starting affix; limits 2 / 3 / 4 (normal / elite / boss).:white:25",
        "#Every 20 days - +1 affix, with health scaling capped at day 100.:white:25",
        "#Normal - 2 starting affixes; limits 3 / 5 / 7.:white:25",
        "#Every 15 days - +1 affix, with health scaling capped at day 150.:white:25",
        "#Hard - 3 starting affixes; limits 5 / 7 / 10.:white:25",
        "#Every 12 days - +1 affix, with health scaling capped at day 200.:white:25",
        "# :white:50",

        "#Dismantling staff:yellow:30",
        "@staff_dis::25:25# Affix stone - enchant equipment.:white:25",
        "@staff_dis::25:25# Cleansing stone - remove an affix.:white:25",
        "@staff_dis::25:25# These shortcuts do not consume materials in the container:yellow:25",
        "@staff_dis::25:25# Gear - remove a gem.:white:25",
        "@staff_dis::25:25# Beefalo horn - punch a socket (uses a socket stone).:white:25",
        "@staff_dis::25:25# Green gem - reroll affix values (uses a reset gem).:white:25",
        "@staff_dis::25:25# Walrus tusk - add a speed gem.:white:25",
        "@staff_dis::25:25# Red gem - add a critical-hit gem.:white:25",
        "@staff_dis::25:25# Volt goat horn - add a boss-damage gem.:white:25",
        "@staff_dis::25:25# Spider silk - add a spider-damage gem.:white:25",
        "@staff_dis::25:25# Stinger - add an insect-damage gem.:white:25",
        "@staff_dis::25:25# Sand stone - add a damage-percent gem.:white:25",
        "@staff_dis::25:25# Steel wool - add a flat-damage gem.:white:25",
        "@staff_dis::25:25# Dragon scales / rhino horn / deerclops eye - treasure-grade gems.:white:25",
        "# :white:50",

        "#Special gems:orange:30",
        "@effect_gem::25:25# Socket stone - adds a gem socket to equipment.:white:25",
        "@effect_gem::25:25# Reset gem - rerolls existing affix values.:white:25",
        "@effect_gem::25:25# Gem remover - destroys one embedded gem at random.:white:25",
        "@effect_gem::25:25# Cleansing token - removes selected affixes at the forge.:white:25",
        "@effect_gem::25:25# Durability gem - restores 1 durability every 2 seconds.:white:25",
        "@effect_gem::25:25# Damage gem - +10 damage.:white:25",
        "@effect_gem::25:25# Power gem - +3% damage.:white:25",
        "@effect_gem::25:25# Speed gem - +3% movement speed.:white:25",
        "@effect_gem::25:25# Night / dusk / day gems - bonus damage at the matching time.:white:25",
        "@effect_gem::25:25# Critical gem - +3% critical chance and +10% critical effect.:white:25",
        "@effect_gem::25:25# Defense / thorns gems - reduce incoming damage or reflect damage.:white:25",
        "@effect_gem::25:25# Species gems - bonus damage against spiders, insects, shadows or bosses.:white:25",
        "@effect_gem::25:25# Follower gems - improve follower damage, defense or critical chance.:white:25",
        "@effect_gem::25:25# Treasure gems - powerful attack, critical or durability effects.:orange:25",
        "# :white:50",

        "#Compatibility:orange:30",
        "#Some multi-slot equipment mods can apply amulet or armor effects to the wrong slot.:white:25",
        "#This can produce incorrect health or damage values.:white:25",
        "#Try Extra Equip Slots (Modified), Workshop ID 2075943614.:white:25",
    },
    help_ui = {
        log_ps = "Note: showing up to the latest 100 world log entries",
    },
    log = {
        type_all = "All",
        type_stone = "Enchanting",
        type_treasure = "Treasure",
        type_egg = "Eggs",
    },
    ui = {
        help_tab_intro = "About the mod",
        help_tab_changes = "Update notes",
        help_tab_effects = "Affix details",
        help_tab_gems = "Gems / Items",
        help_tab_logs = "Log",
        help_title_intro = "About Starforge",
        help_title_changes = "Update notes",
        help_title_effects = "Affix effects",
        help_title_gems = "Gems / Items",
        help_title_logs = "World log",
        open_forge_hint = "Open forge (hotkey: %s)\nRight-click and drag to move",
        open_forge_label = "Forge",
    },
}
