----
---多语言文本
---
local HH_LANGUAGE = {
    affix_ui = {
        no_range = "无取值范围",
        only_one = "只允许存在一条",
        repeatable = "可重复附魔",
        regular = "可以通过普通附魔获取",
        rare = "精英/boss掉落的专属附魔石/武器包裹",
        crafting = "只能从合成台较低概率合成出来",
        none = "无",
        description = "描述:",
        uniqueness = "唯一性:",
        source = "来源:",
        prerequisite = "前置条件:",
    },
    hover_config = {
        open_hint = "信息面板配置\n右键拖拽位置",
        open_label = "面版配置",
        background = "面板配置\n背景颜色",
        opacity = "透明度",
        decrease = "减",
        increase = "加",
        border = "边框颜色",
        corners = "四\n角\n图\n标",
        none = "无",
        top_left = "左上",
        bottom_left = "左下",
        top_right = "右上",
        bottom_right = "右下",
        all = "全部",
        apply = "应用边框",
        hide = "关闭显示",
        show = "打开显示",
    },
    help_ui = {
        original_guide = "B站Mod介绍链接-By:风萧听雨落",
        changelog_title = "星砧更新记录",
        changelog_desc = "星砧版本记录见 github.com/VHcat/dst-starforge/releases。原模组历史记录仍可查看。",
        open_hint = "mod帮助\n右键拖拽位置",
        open_label = "帮助",
        undefined_title = "未定义标题",
        undefined_affix = "词条未定义",
        undefined_desc = "描述未定义",
        empty = "空",
        removed_set = "套装(已移除):",
        effect = "效果:",
        probability = "概率表",
    },
    forge = {
        undefined = "未定义",
        empty = "空",
        read_failed = "读取失败",
        none_selected = "未选择清除词条",
        remove_selected = "消耗%s个净化符\n清除选中的词条",
        confirm = "确认",
        cancel = "取消",
        recipe = "词条配方",
        old_equipment = "原装备",
        empty_equipment = "装备(无词条)",
        inherit_button = "继承",
        cost = "消耗:",
        crystal_figure = "水晶小人",
        nightmare_fuel = "噩梦燃料",
        inherit_header = "<装备继承>",
        inherit_1 = "将一件装备上的词条转移给另一个装备上",
        inherit_2 = "下方格子放消耗材料",
        inherit_3 = "继承成功后 原装备会消失",
        inherit_4 = "装备a的某些词条 装备b不满足词条的前置条件",
        inherit_5 = "该词条不会被继承",
        inherit_6 = "装备a必须存在词条，装备b必须是无词条状态",
        combine_button = "合成",
        combine_header = "<词条三合一>",
        combine_1 = "将三个附魔石合成",
        combine_2 = "百分之一概率合成出极品附魔石",
        convert_button = "转换",
        convert_header = "<附魔石转换>",
        convert_material = "材料:附魔石+水晶小人*%s",
        convert_chance = "可以将附魔石随机一次属性,%s%%概率产生稀有词条",
        convert_rare = "%s%%概率产生超级稀有词条",
        craftable_affixes = "可合成的词条",
        equipment_arrow = "装备==>",
        materials = "材\n料",
        star_chance = "星级装备\n提升概率",
        upgrade_button = "强化",
        star_up_button = "升星",
        repair_button = "修复",
        name_label = "名字:",
        bind_label = "绑定:",
        star_label = "星级:",
        star_probability = "升星概率:",
        star_materials = "升星材料:",
        repair_materials = "修复材料:",
        draw = "抽奖", inherit = "继承", enhance = "强化",
        selective_clear = "<定向清除>",
        clear_help = "可以自由选择清除指定位置的词条",
        clear_cost = "消耗:净化符(宝石页面查看)",
        clear_quantity = "消耗数量等同于选择的词条数量",
        clear = "清除",
    },
    equip_ui = {
        move_confirm = "一键放入装备",
        dismantle_confirm = "是否拆除装备",
        reroll_confirm = "刷新装备所有词条的属性",
        enchant_confirm = "对装备进行附魔",
        clear_confirm = "随机清除一个词条",
        empty = "空",
        socket_confirm = "是否镶嵌",
        punch_confirm = "是否给装备打孔",
        remove_gem_confirm = "是否随机销毁一个宝石",
        use_item = "使用%s",
        title = "装备强化", put_in = "一键放入", dismantle = "一键拆解",
        equip = "↑\n装\n备", enchant_item = "↑\n附\n魔\n类",
        cleansing_item = "↑\n洗\n蕴\n石",
        upgrade = "升品", enchant = "附魔", clear = "清除",
        enchant_hint = "[附魔石/卷轴]:给装\n备增加指定/随机词条",
        reroll_hint = "[重置宝石]:将装备数值\n类词条进行随机赋值",
        clear_hint = "[洗蕴石]:随机清除一个词\n条",
        gem_title = "宝石镶嵌",
        inventory_hint = "↓已有物品(空白就是啥都没有)↓",
        equipment_hint = "装备→", gem = "宝石",
        confirm = "确认", cancel = "取消",
    },
    ["ui"] = {
        action_use = "进行操作",
        action_treasure = "寻宝",
        container_dismantle = "拆解",
        container_convert = "转换",
        container_gold = "转换金子",
        container_stone = "转换沙石",
        rename_placeholder = "名字",
        help_tab_intro = "mod介绍",
        help_tab_changes = "更新记录",
        help_tab_effects = "词条详情",
        help_tab_gems = "宝石/道具",
        help_tab_logs = "日志",
        help_title_intro = "传奇武器mod介绍",
        help_title_changes = "更新日志",
        help_title_effects = "词条属性",
        help_title_gems = "宝石/道具",
        help_title_logs = "世界日志",
        open_forge_hint = "打开强化页面(当前热键:%s)\n右键拖拽位置",
        open_forge_label = "强化空间",
    },
    ["item"] = {
    },
    ["mod_help"] = {
        --"#附魔部分:white:30@effect_stone::30:30#2222:red:30#3333:yellow:30@remove_stone::30:30#结尾:yellow:30",
        "#玩法:orange:30",
        "#1.怪物初始会自带随机的强化词条(每天血量上限会进行提升):white:25",
        "#2.击杀强化的怪物有概率掉落含有特殊词条的装备:white:25",
        "#3.含有词条的装备有10%概率(词条数>=3必出)拆解出带有词条的附魔石:white:25",
        "#4.精英/boss标签的怪物死亡时，有概率掉落含有极品词条的装备包裹/附魔石:white:25",
        "#5.击杀任意生物有概率获得 :white:25@effect_tally::25:25#/:white:25@remove_stone::25:25",
        "#6.击杀任意生物有概率获得特殊:white:25@effect_gem::25:25#(非物品栏道具，仅限强化栏-宝石区查看):white:25",
        "#7.:white:25@magic::25:25#可制作:white:25@suit_build::25:25#：装备继承 定向清除:white:25",
        "#8.:white:25@suit_build::25:25#中 升品-对装备所有词条的值进行随机-需要特殊道具-重置宝石:white:25@remove_stone::25:25",
        "# :white:50",

        "#物品介绍:orange:30",
        "@effect_tally::25:25#-对装备进行一次随机附魔[:white:25@suit_build::25:25#中操作]:white:25",
        "@remove_stone::25:25#-随机清除装备的一条词条[:white:25@suit_build::25:25#中操作]:white:25",
        "@essence::25:25#-通用材料:white:25",
        "@cat_box::25:25#-便携附魔盒子[可一键分解:white:25@effect_stone::25:25@arrow_right::25:25@essence::25:25#]:white:25",
        "@duck_box::25:25#-便捷式猪王:white:25",
        "@staff_dis::25:25#-右键分解装备[装备:white:25@arrow_right::25:25@effect_stone::25:25#或:white:25@effect_stone::25:25@arrow_right::25:25@essence::25:25#]:white:25",
        "@ice_knife::25:25#-攻击有概率发出三束范围伤害的火焰:white:25",
        "@staff_star::25:25#-远程武器[三发弹道]:white:25",
        "@treasure_tally::25:25#-右键发现宝藏[:white:25@treasure_build::25:25#]:white:25",
        "@treasure_build::25:25#-宝藏点[奇遇/强化生物]:white:25",
        "@egg_nest::25:25#-孵蛋窝/展示台[建筑栏制作，可孵化/展示各种品质的蛋]:white:25",
        --蛋
        "#\t\t普通品质[普通生物随机掉落]:white:25@egg_common::25:25",
        "#\t\t珍贵品质[精英生物随机掉落]:white:25@egg_silver::25:25",
        table["concat"]({
            "#\t\t稀有品质[boss生物随机掉落]:white:25",
            "@egg_gold::25:25",
            "@egg_cat_claw_orange::25:25",
            "@egg_cat_claw_purple::25:25",
            "@egg_cat_claw_green::25:25",
            "@egg_cat_claw_blue::25:25",
            "@egg_figure_blue_star::25:25",
            "@egg_figure_green_black::25:25",
            "@egg_figure_purple_black::25:25",
            "@egg_figure_red_black::25:25",
            "@egg_figure_red_blue::25:25",
            "@egg_figure_yellow_green::25:25",
            "@egg_figure_yellow_green_purple::25:25",
        }, ""),
        "#\t\t星空品质[宝藏获取]:white:25@egg_starry_sky::25:25",
        "#\t\t欧皇象征[欧皇无需多言]:white:25@egg_black::25:25",
        "@hat_star::25:25#-可升星的王冠[孵蛋概率掉落,升星在:white:25@suit_build::25:25#中操作]:white:25",
        "# :white:50",

        "#怪物难度配置:orange:30",
        "#1.简单:white:25",
        "#初始词条1条-额外血量:white:25",
        "#词条上限：:white:25#[普通]-2 :white:25#[精英]-3 :orange:25#[boss]-4 :red:25",
        "#每:white:25#20天:yellow:25#增加一个词条 额外血量加成-天数上限-:white:25#100天:yellow:25",
        "#2.普通:white:25",
        "#初始词条2条:white:25",
        "#词条上限：:white:25#[普通]-3 :white:25#[精英]-5 :orange:25#[boss]-7 :red:25",
        "#每:white:25#15天:yellow:25#增加一个词条 额外血量加成-天数上限-:white:25#150天:yellow:25",
        "#3.困难:white:25",
        "#初始词条3条:white:25",
        "#词条上限：:white:25#[普通]-5 :white:25#[精英]-7 :orange:25#[boss]-10 :red:25",
        "#每:white:25#12天:yellow:25#增加一个词条 额外血量加成-天数上限-:white:25#200天:yellow:25",
        "# :white:50",

        "#拆除法杖-道具拓展:orange:30",
        "@staff_dis::25:25#附魔石：装备附魔:white:25",
        "@staff_dis::25:25#洗蕴石：清除词条:white:25",
        "@staff_dis::25:25#以下不消耗容器中的材料:yellow:25",
        "@staff_dis::25:25#齿轮：使用解石器:white:25",
        "@staff_dis::25:25#牛角：装备打孔(消耗打孔石):white:25",
        "@staff_dis::25:25#绿宝石：刷新词条数值(消耗重置宝石):white:25",
        "@staff_dis::25:25#海象牙：镶嵌步伐珠(已打孔):white:25",
        "@staff_dis::25:25#红宝石：镶嵌暴击石(已打孔):white:25",
        "@staff_dis::25:25#电羊角：镶嵌首领打击(已打孔):white:25",
        "@staff_dis::25:25#蜘蛛丝：镶嵌蜘蛛打击(已打孔):white:25",
        "@staff_dis::25:25#蜂刺：镶嵌昆虫打击(已打孔):white:25",
        "@staff_dis::25:25#沙之石：镶嵌力势石(已打孔):white:25",
        "@staff_dis::25:25#刚羊毛：镶嵌增伤宝珠(已打孔):white:25",
        "@staff_dis::25:25#龙蝇皮：镶嵌宝★攻击(已打孔):white:25",
        "@staff_dis::25:25#犀牛角：镶嵌宝★暴击(已打孔):white:25",
        "@staff_dis::25:25#巨鹿眼球：镶嵌宝★回耐(已打孔):white:25",
        "# :white:50",

        "#概率表:orange:30",
        string["format"]("#装备-普通生物：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["DROP_EQUIP_CHANCE"]["common_monster"] * 100),
        string["format"]("#装备-精英生物：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["DROP_EQUIP_CHANCE"]["elite_monster"] * 100),
        string["format"]("#装备-boss生物：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["DROP_EQUIP_CHANCE"]["boss_monster"] * 100),
        string["format"]("#宝石/特殊道具：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["GIF_CHANCE"]["player_gem_chance"] * 100),
        string["format"]("#附魔卷轴/洗蕴石：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["GIF_CHANCE"]["player_stone_chance"] * 50),
        string["format"]("#极品附魔石-精英：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["GIF_CHANCE"]["elite_monster_stone"] * 100),
        string["format"]("#极品附魔石-boss：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["GIF_CHANCE"]["boss_monster_stone"] * 100),
        string["format"]("#装备包裹-精英：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["GIF_CHANCE"]["elite_monster_gif"] * 100),
        string["format"]("#装备包裹-boss：%s%%:white:25", TUNING["HH_CHANCE_CONFIG"]["GIF_CHANCE"]["boss_monster_gif"] * 100),
        "# :white:50",

        "#特殊宝石:orange:30",
        "@effect_gem::25:25#打孔石-给装备打孔(装备镶嵌珠宝的前置条件):white:25",
        "@effect_gem::25:25#重置宝石-针对装备已有词条数值进行重新随机数值(点击升品按钮):white:25",
        "@effect_gem::25:25#解石器-随机销毁一个已经镶嵌的宝石:white:25",
        "@effect_gem::25:25#净化符-用于合成台页面清除词条:white:25",
        "@effect_gem::25:25#耐用宝珠-每2s增加装备1点耐久:white:25",
        "@effect_gem::25:25#增伤宝珠-增加造成的伤害10点:white:25",
        "@effect_gem::25:25#力势石-造成的伤害增加3%:white:25",
        "@effect_gem::25:25#步伐珠-移速增加3%:white:25",
        "@effect_gem::25:25#暗袭珠-夜晚造成伤害增加20点:white:25",
        "@effect_gem::25:25#昏光珠-黄昏伤害增加20点:white:25",
        "@effect_gem::25:25#光耀珠-白天伤害增加20点:white:25",
        "@effect_gem::25:25#暴击石-暴击+3%，暴击效果+10%:white:25",
        "@effect_gem::25:25#抗伤石-受到的伤害减少3点:white:25",
        "@effect_gem::25:25#反伤石-受到伤害时，反弹3点伤害给攻击者:white:25",
        "@effect_gem::25:25#蜘蛛打击-对蜘蛛造成的伤害增加20点:white:25",
        "@effect_gem::25:25#昆虫打击-对昆虫造成的伤害增加20点:white:25",
        "@effect_gem::25:25#暗影打击-对暗影生物造成的伤害增加20点:white:25",
        "@effect_gem::25:25#首领打击-对boss造成的伤害增加50点:white:25",
        "@effect_gem::25:25#灵兽-暴-提升随从暴击率3%:white:25",
        "@effect_gem::25:25#灵兽-攻-提升随从伤害10点:white:25",
        "@effect_gem::25:25#灵兽-御-随从受到的伤害减少3点:white:25",
        "@effect_gem::25:25#宝★攻击-伤害+50:orange:25",
        "@effect_gem::25:25#宝★暴击-暴击率+20%:orange:25",
        "@effect_gem::25:25#宝★回耐-同极品回耐:orange:25",
        "# :white:50",

        "#兼容问题:orange:30",
        "#某些多格装备栏由于自身逻辑问题：穿戴护符/护甲执行另一个装备栏物品函数:white:25",
        "#导致属性错乱(生命/攻击无限上限):white:25",
        "#解决方案：换个五格:white:25",
        "#推荐：Extra Equip Slots (Modified) 工坊id：2075943614:white:25",
    },
    ["help_ui"] = {
        ["log_ps"] = "PS:默认只展示前100条日志(当前世界)",
    },
    ["log"] = {
        ["type_all"] = "全部",
        ["type_stone"] = "附魔",
        ["type_treasure"] = "宝藏",
        ["type_egg"] = "孵蛋",
        ["compound_stone_best"] = "#{{data_player}}:yellow:25#通过:white:25@suit_build::25:25#合成出:white:25@effect_stone::25:25#[{{data_effect}}]:orange:25#[已消耗:green:25@essence::25:25#-{{data_essence}}]:green:25",
        ["compound_stone_rare"] = "#{{data_player}}:yellow:25#通过:white:25@suit_build::25:25#合成出:white:25@effect_stone::25:25#[{{data_effect}}]:red:25#[已消耗:green:25@essence::25:25#-{{data_essence}}]:green:25",
        ["compound_black_egg"] = "#[欧皇]:yellow:25#{{data_player}}:yellow:25#通过:white:25@suit_build::25:25#获得:yellow:25@egg_black::25:25#一枚:white:25#",
        ["dig_treasure_monster"] = "#{{data_player}}:yellow:25#在:white:25@treasure_build::25:25#中挖出:white:25@{{data_image}}::25:25#[{{data_monster}}]:yellow:25",
        ["kill_treasure_kps"] = "#{{data_player}}:yellow:25#s拿下坎普斯大王的尾刀，奖励特殊宝石三份:white:25",
        ["kill_treasure_cat_you"] = "#{{data_player}}:yellow:25#暴打超级猫悠大王，奖励稀有附魔石三份:white:25",
        ["kill_treasure_boss"] = "#{{data_player}}:yellow:25#拿下:white:25#[{{data_monster}}]:red:25#的尾刀，奖励特殊宝石一份:white:25#[{{data_gem}}]:orange:25",
    },
    ["gem"] = {
        ["treasure_atk"] = "宝★攻击",
        ["treasure_bj"] = "宝★暴击",
        ["treasure_armor"] = "宝★回耐",
    },
}
return HH_LANGUAGE
