-- English text is added section by section. Missing entries fall back to Chinese.
return {
    fx_text = {
        ["治疗"] = "Healing",
        ["中毒"] = "Poisoned",
        ["减速"] = "Slowed",
        ["制裁"] = "Healing Blocked",
        ["流血"] = "Bleeding",
        ["移速强化"] = "Speed Boost",
        ["控制"] = "Stunned",
        ["格挡"] = "Blocked",
        ["双倍"] = "Double",
        ["三倍"] = "Triple",
        ["五倍"] = "Fivefold",
        ["暴击"] = "Critical Hit",
        ["闪避"] = "Dodged",
        ["飞云逸影触发"] = "Cloudstep Triggered",
        ["永恒庇佑触发"] = "Eternal Blessing",
        ["穿刺"] = "Piercing",
        ["帅"] = "Handsome",
        ["枝江糕手"] = "Zhijiang Master",
        ["技艺过人"] = "Masterful",
        ["豁达大度"] = "Open-minded",
        ["超凡脱俗"] = "Extraordinary",
        ["技术超群"] = "Superb Skill",
        ["登峰造极"] = "At the Peak",
        ["融会贯通"] = "All-round Talent",
        ["精湛无比"] = "Exquisite Skill",
        ["睿智超群"] = "Brilliant Mind",
        ["技术一流"] = "Top-notch Skill",
        ["博古通今"] = "Learned",
        ["才华横溢"] = "Overflowing Talent",
        ["学富五车"] = "Well Read",
        ["技术卓越"] = "Excellent Skill",
        ["才高八斗"] = "Gifted Scholar",
        ["才华横盛"] = "Great Talent",
        ["才华出众"] = "Outstanding Talent",
        ["泰山北斗"] = "Leading Master",
        ["技术娴熟"] = "Highly Skilled",
        ["才气纵横"] = "Brilliant Talent",
        ["技艺精湛"] = "Exquisite Craft",
        ["技术非凡"] = "Exceptional Skill",
        ["睿智过人"] = "Remarkable Wisdom",
        ["技术精湛"] = "Master Craft",
        ["聪颖绝伦"] = "Bright Mind",
        ["才华洋溢"] = "Full of Talent",
        ["博大精深"] = "Deep Learning",
        ["渊博高深"] = "Profound Knowledge",
        ["技术一绝"] = "One of a Kind",
        ["技巧高超"] = "Superb Technique",
        ["才思敏捷"] = "Quick Thinking",
        ["技术独到"] = "Unique Technique",
        ["神龙见首"] = "Elusive Dragon",
        ["技压群雄"] = "Best in Class",
        ["技法精湛"] = "Fine Technique",
        ["才华横流"] = "Boundless Talent",
        ["神乎其技"] = "Divine Skill",
        ["出神入化"] = "Perfected Craft",
        ["出类拔萃"] = "Standing Out",
        ["一技之长"] = "A Special Talent",
        ["技术过硬"] = "Proven Skill",
        ["才思敏锐"] = "Sharp Mind",
        ["才气横溢"] = "Inspired Talent",
        ["技艺高超"] = "Expert Craft",
        ["渊博精深"] = "Deep Expertise",
        ["技术高明"] = "Clever Technique",
        ["技艺超群"] = "Unrivaled Craft",
        ["技术了得"] = "Remarkable Skill",
        ["技艺出众"] = "Outstanding Craft",
        ["技术过人"] = "Expert Hands",
        ["悟性超群"] = "Unrivaled Insight",
    },
    affixes = {
        restore_use_10s_1use = {
            name = "Durability Regen (10s)", short = "10s\nRegen",
            desc = "Restores 1 durability every 10 seconds.",
            check = "Armor, fuel, uses, freshness",
        },
        restore_use_5s_1use = {
            name = "Durability Regen (5s)", short = "5s\nRegen",
            desc = "Restores 1 durability every 5 seconds.",
            check = "Armor, fuel, uses, freshness",
        },
        restore_use_3s_1use = {
            name = "Durability Regen (3s)", short = "3s\nRegen",
            desc = "Restores 1 durability every 3 seconds.",
            check = "Armor, fuel, uses, freshness",
        },
        restore_use_1s_2_percent = {
            name = "Greater Durability Regen", short = "Rare\nRegen",
            desc = "Restores 2 percent durability every second.",
            check = "Armor, fuel, uses, freshness",
        },
        add_max_use = {
            name = "Increased Durability", short = "Durable",
            desc = "Increases equipment durability by %s.",
            check = "Armor, fuel, uses, freshness",
        },
        add_max_use_armor_01 = {
            name = "Armor Durability (Small)", short = "Small\nArmor",
            desc = "Increases armor durability by %s.",
            check = "Armor",
        },
        add_max_use_armor_02 = {
            name = "Armor Durability (Medium)", short = "Med\nArmor",
            desc = "Increases armor durability by %s.",
            check = "Armor",
        },
        add_max_use_armor_03 = {
            name = "Armor Durability (Large)", short = "Large\nArmor",
            desc = "Increases armor durability by %s.",
            check = "Armor",
        },
        reduce_com_attacked_damage = {
            name = "Flat Damage Reduction", short = "Damage\nResist",
            desc = "Reduces incoming damage by %s.",
            check = "Non-weapon equipment",
        },
        add_com_damage = {
            name = "Bonus Damage", short = "Damage\nBoost",
            desc = "Increases damage dealt by %s.",
            check = "None",
        },
        add_night_damage = {
            name = "Night Damage", short = "Night\nDamage",
            desc = "Increases damage dealt at night by %s.",
            check = "None",
        },
        add_day_damage = {
            name = "Day Damage", short = "Day\nDamage",
            desc = "Increases damage dealt during the day by %s.",
            check = "None",
        },
        add_dusk_damage = {
            name = "Dusk Damage", short = "Dusk\nDamage",
            desc = "Increases damage dealt at dusk by %s.",
            check = "None",
        },
        add_moisture_damage = {
            name = "Wet Damage", short = "Wet\nDamage",
            desc = "Increases damage dealt while wet by %s.",
            check = "None",
        },
        blood_outburst = {
            name = "Blood Outburst", short = "Low HP\nDamage",
            desc = "Damage rises as health falls, up to 50 percent.",
            check = "None",
        },
        spirit_fade = {
            name = "Spirit Fade", short = "Low SAN\nDamage",
            desc = "Damage rises as sanity falls, up to 50 percent.",
            check = "None",
        },
        hunger_assault = {
            name = "Hunger Assault", short = "Low Food\nDamage",
            desc = "Damage rises as hunger falls, up to 50 percent.",
            check = "None",
        },
        reflexive_injury = {
            name = "Damage Reflection", short = "Reflect",
            desc = "Reflects %s damage to attackers when hit.",
            check = "Non-weapon equipment",
        },
        add_hit_damage_pig = {
            name = "Pig Slayer", short = "Pig\nDMG",
            desc = "Deals %s more damage to pigs.",
            check = "None",
        },
        add_hit_damage_fish = {
            name = "Merm Slayer", short = "Merm\nDMG",
            desc = "Deals %s more damage to fish and merms.",
            check = "None",
        },
        add_hit_damage_monkey = {
            name = "Monkey Slayer", short = "Monkey\nDMG",
            desc = "Deals %s more damage to monkeys.",
            check = "None",
        },
        add_hit_damage_gear = {
            name = "Clockwork Slayer", short = "Gear\nDMG",
            desc = "Deals %s more damage to clockwork creatures.",
            check = "None",
        },
        add_hit_damage_spider = {
            name = "Spider Slayer", short = "Spider\nDMG",
            desc = "Deals %s more damage to spiders.",
            check = "None",
        },
        add_hit_damage_dog = {
            name = "Hound Slayer", short = "Hound\nDMG",
            desc = "Deals %s more damage to hounds.",
            check = "None",
        },
        add_hit_damage_frog = {
            name = "Frog Slayer", short = "Frog\nDMG",
            desc = "Deals %s more damage to frogs.",
            check = "None",
        },
        add_hit_damage_insect = {
            name = "Insect Slayer", short = "Bug\nDMG",
            desc = "Deals %s more damage to insects.",
            check = "None",
        },
        add_hit_damage_shadow = {
            name = "Shadow Slayer", short = "Shadow\nDMG",
            desc = "Deals %s more damage to shadow creatures.",
            check = "None",
        },
        add_hit_damage_boss = {
            name = "Giant Slayer", short = "Boss\nDMG",
            desc = "Deals %s more damage to giants.",
            check = "None",
        },
        add_hit_damage_plant = {
            name = "Plant Slayer", short = "Plant\nDMG",
            desc = "Deals %s more damage to plants.",
            check = "None",
        },
        add_extra_damage_percent = {
            name = "Damage Bonus", short = "Damage\nBonus",
            desc = "Increases damage dealt by %s percent.",
            check = "None",
        },
        add_critical_hit_rate = {
            name = "Critical Chance", short = "Crit\nChance",
            desc = "Grants %s percent critical-hit chance.",
            check = "None",
        },
        add_critical_hit_effect = {
            name = "Critical Damage", short = "Crit\nDMG",
            desc = "Increases critical-hit damage by %s percent.",
            check = "None",
        },
        atk_blood_01 = {
            name = "Minor Lifesteal", short = "Minor\nLeech",
            desc = "Restores health equal to %s percent of damage dealt.",
            check = "Combat equipment only",
        },
        atk_blood_suck_02 = {
            name = "Major Lifesteal", short = "Major\nLeech",
            desc = "Restores health equal to %s percent of damage dealt.",
            check = "Combat equipment only",
        },
        atk_blood_suck_03 = {
            name = "Supreme Lifesteal", short = "Rare\nLeech",
            desc = "Restores health equal to %s percent of damage dealt.",
            check = "Combat equipment only",
        },
        atk_add_good_damage = {
            name = "Supreme Damage", short = "Rare\nDMG",
            desc = "Increases damage dealt by %s.",
            check = "None",
        },
        reduce_good_damage = {
            name = "Supreme Defense", short = "Rare\nGuard",
            desc = "Reduces incoming damage by %s.",
            check = "Non-weapon equipment",
        },
        atk_add_san = {
            name = "Sanity Siphon", short = "Sanity\nLeech",
            desc = "Restores sanity equal to %s percent of damage dealt.",
            check = "Combat equipment only",
        },
        add_speed_percent = {
            name = "Swiftness", short = "Move\nSpeed",
            desc = "Increases movement speed by %s percent.",
            check = "None",
        },
        add_max_health_01 = {
            name = "Minor Health", short = "Minor\nHealth",
            desc = "Increases maximum health by %s.",
            check = "None",
        },
        add_max_health_02 = {
            name = "Medium Health", short = "Med\nHealth",
            desc = "Increases maximum health by %s.",
            check = "None",
        },
        add_max_health_03 = {
            name = "Major Health", short = "Major\nHealth",
            desc = "Increases maximum health by %s.",
            check = "None",
        },
        add_max_health_04 = {
            name = "Supreme Health", short = "Rare\nHealth",
            desc = "Increases maximum health by %s.",
            check = "None",
        },
        atk_10s_health = {
            name = "Healing Trigger", short = "Heal\nTrigger",
            desc = "Attacks may grant 10 seconds of health regeneration (+1).",
            check = "None",
        },
        add_critical_hit_rate_damage = {
            name = "Endless Critical", short = "Rare\nCrit",
            desc = "Grants %s percent critical chance and 100 percent critical damage.",
            check = "Unique",
        },
        add_immune_cold = {
            name = "Cold Immunity", short = "Cold\nImmune",
            desc = "Prevents freezing from cold.",
            check = "None",
        },
        add_immune_hot = {
            name = "Heat Immunity", short = "Heat\nImmune",
            desc = "Prevents overheating.",
            check = "None",
        },
        add_immune_poison = {
            name = "Poison Immunity", short = "Poison\nImmune",
            desc = "Prevents poison damage.",
            check = "None",
        },
        add_immune_freeze = {
            name = "Freeze Immunity", short = "Freeze\nImmune",
            desc = "Prevents freezing.",
            check = "None",
        },
        immune_debuff = {
            name = "Elemental Defense", short = "Element\nGuard",
            desc = "Protects against cold, heat, freezing and poison.",
            check = "None",
        },
        immune_bramble = {
            name = "Reflection Immunity", short = "Reflect\nImmune",
            desc = "Prevents reflected damage.",
            check = "None",
        },
        san_replace_damage = {
            name = "Shadow Shield", short = "Shadow\nShield",
            desc = "Has a %s percent chance to spend sanity instead of taking damage.",
            check = "None",
        },
        atk_add_poison = {
            name = "Poison Strike", short = "Poison\nStrike",
            desc = "Has a %s percent chance to poison a monster, dealing 5 damage every 2 seconds for 60 seconds.",
            check = "None",
        },
        reduce_bramble_percent = {
            name = "Thorns Resistance", short = "Thorns\nResist",
            desc = "Reduces reflected damage taken by %s percent.",
            check = "None",
        },
        follow_add_damage = {
            name = "Follower Damage", short = "Follower\nDMG",
            desc = "Increases follower damage by %s.",
            check = "None",
        },
        follow_reduce_damage = {
            name = "Follower Defense", short = "Follower\nGuard",
            desc = "Reduces damage taken by followers by %s.",
            check = "None",
        },
        health_suppress_num = {
            name = "Judgement", short = "Judgement",
            desc = "Has a %s percent chance to apply Judgement for 10 seconds.",
            check = "None",
        },
        more_damage_20_200 = {
            name = "Double Damage", short = "Double\nDMG",
            desc = "20 percent chance to deal %s percent damage; can critically hit.",
            check = "Unique",
        },
        more_damage_15_300 = {
            name = "Triple Damage", short = "Triple\nDMG",
            desc = "15 percent chance to deal %s percent damage; can critically hit.",
            check = "Unique",
        },
        more_damage_8_500 = {
            name = "Quintuple Damage", short = "Fivefold\nDMG",
            desc = "8 percent chance to deal %s percent damage; can critically hit.",
            check = "Unique",
        },
        true_damage_small = {
            name = "Minor True Damage", short = "Minor\nPierce",
            desc = "Adds %s true damage on hit.",
            check = "Combat equipment only",
        },
        true_damage_big = {
            name = "Major True Damage", short = "Major\nPierce",
            desc = "Adds %s true damage on hit.",
            check = "Combat equipment only",
        },
        target_percent_damage = {
            name = "Rending Strike", short = "Rend",
            desc = "Adds %s percent of the target's current health to damage.",
            check = "Combat equipment only",
        },
        shadow_camp = {
            name = "Shadow Disguise", short = "Shadow\nDisguise",
            desc = "Shadow creatures do not become hostile to the player.",
            check = "None",
        },
        moon_camp = {
            name = "Lunar Disguise", short = "Lunar\nDisguise",
            desc = "Lunar creatures do not initiate hostility.",
            check = "None",
        },
        immunity_moisture = {
            name = "Wetness Immunity", short = "Dry",
            desc = "Prevents wetness.",
            check = "None",
        },
        add_light = {
            name = "Light Source", short = "Light",
            desc = "Emits light.",
            check = "None",
        },
        fast_act = {
            name = "Quick Actions", short = "Quick\nActions",
            desc = "Greatly speeds up gathering, building, cooking and trading.",
            check = "None",
        },
        work_speed = {
            name = "Double Work", short = "Double\nWork",
            desc = "Doubles work speed.",
            check = "None",
        },
        armor_reduce_amount_small = {
            name = "Minor Armor Conservation", short = "Minor\nArmor",
            desc = "Reduces armor durability loss on hit by %s percent.",
            check = "Armor with durability",
        },
        armor_reduce_amount = {
            name = "Major Armor Conservation", short = "Major\nArmor",
            desc = "Reduces armor durability loss on hit by %s percent.",
            check = "Armor with durability",
        },
        porter = {
            name = "Porter", short = "Porter",
            desc = "Carrying a statue does not slow you down.",
            check = "Head slot only",
        },
        atk_speed_small = {
            name = "Minor Attack Speed", short = "Minor\nSpeed",
            desc = "Increases attack speed by %s percent (subject to mod setting).",
            check = "Hand slot only",
        },
        atk_speed_big = {
            name = "Major Attack Speed", short = "Major\nSpeed",
            desc = "Increases attack speed by %s percent (subject to mod setting).",
            check = "Hand slot only",
        },
        immune_sleep = {
            name = "Sleep Immunity", short = "Sleep\nImmune",
            desc = "Prevents sleep effects.",
            check = "Hand slot only",
        },
        absorb_small = {
            name = "Minor Damage Absorption", short = "Minor\nGuard",
            desc = "Reduces incoming damage by %s percent.",
            check = "None",
        },
        absorb_middle = {
            name = "Medium Damage Absorption", short = "Med\nGuard",
            desc = "Reduces incoming damage by %s percent.",
            check = "None",
        },
        absorb_big = {
            name = "Major Damage Absorption", short = "Major\nGuard",
            desc = "Reduces incoming damage by %s percent.",
            check = "None",
        },
        autumn_god = {
            name = "Autumn Warrior", short = "Autumn\nWarrior",
            desc = "In autumn, grants 50 bonus damage and 10 percent critical chance.",
            check = "None",
        },
        black_monkey = {
            name = "Curse Trinket Power", short = "Curse\nPower",
            desc = "Each cursed trinket in inventory increases damage by %s percent, up to 100 percent.",
            check = "None",
        },
        tga_robot = {
            name = "Cosmic Robot", short = "Robot\nPower",
            desc = "Robots gain %s bonus damage.",
            check = "None",
        },
        money_player = {
            name = "Gold Spender", short = "Gold\nPower",
            desc = "Spends gold for 100 bonus damage; without gold, damage falls by 200.",
            check = "One effective copy only",
        },
        immunity_stick = {
            name = "Slime Immunity", short = "Slime\nImmune",
            desc = "Prevents slime effects.",
            check = "None",
        },
        armor_immune_amount = {
            name = "Rare: Armor Lock", short = "Rare\nArmor",
            desc = "Armor does not lose durability when hit.",
            check = "Armor with durability; absorption below 100 percent",
        },
        special_bhtg = {
            name = "Rare: White Tiger", short = "White\nTiger",
            desc = "Grants 3 percent sanity steal, 3 percent lifesteal, 50 bonus damage, 10 percent damage bonus and Judgement.",
            check = "Weapons only",
        },
        special_zqrf = {
            name = "Rare: Vermilion Bird", short = "Vermilion\nBird",
            desc = "Immune to Judgement, slow, cold, heat, freezing, poison and wetness.",
            check = "None",
        },
        special_true_damage = {
            name = "Rare: True Damage", short = "Rare\nPierce",
            desc = "Adds %s true damage on hit.",
            check = "None",
        },
        special_sgsy = {
            name = "Rare: Tortoise Guard", short = "Tortoise\nGuard",
            desc = "Reduces flat damage by 35 and remaining damage by 45 percent; immune to reflected damage.",
            check = "None",
        },
        special_immune_control = {
            name = "Rare: Control Immunity", short = "Control\nImmune",
            desc = "Immune to knockback, ewecus and slurper slime, sleep and freezing.",
            check = "None",
        },
    },
    affix_ui = {
        no_range = "No variable value",
        only_one = "Only one allowed",
        repeatable = "Can be repeated",
        regular = "Available from regular enchanting",
        rare = "Elite / boss drop",
        crafting = "Only available through forging",
        none = "None",
        description = "Effect: ",
        uniqueness = "Stacking: ",
        source = "Source: ",
        prerequisite = "Requirement: ",
    },
    hover_config = {
        open_hint = "Info panel settings\nRight-click and drag to move",
        open_label = "Panel settings",
        background = "Panel background color",
        opacity = "Opacity",
        decrease = "Less",
        increase = "More",
        border = "Border color",
        corners = "Corner icons",
        none = "None",
        top_left = "Top left",
        bottom_left = "Bottom left",
        top_right = "Top right",
        bottom_right = "Bottom right",
        all = "All",
        apply = "Apply border",
        hide = "Hide panel",
        show = "Show panel",
    },
    forge = {
        undefined = "Unknown",
        empty = "Empty",
        read_failed = "Failed to read",
        none_selected = "No affixes selected",
        remove_selected = "Spend %s Cleansing Tokens\nto remove selected affixes",
        confirm = "Confirm",
        cancel = "Cancel",
        recipe = "Affix recipes",
        old_equipment = "Original gear",
        empty_equipment = "Gear (no affixes)",
        inherit_button = "Inherit",
        cost = "Cost:",
        crystal_figure = "Crystal Figure",
        nightmare_fuel = "Nightmare Fuel",
        inherit_header = "<Equipment Inheritance>",
        inherit_1 = "Move affixes from one piece of gear to another.",
        inherit_2 = "Place the required materials in the slots below.",
        inherit_3 = "The original gear is consumed on success.",
        inherit_4 = "Some affixes on gear A may not meet gear B's requirements.",
        inherit_5 = "Those affixes will not transfer.",
        inherit_6 = "Gear A needs affixes; gear B must have none.",
        combine_button = "Combine",
        combine_header = "<Combine Three Affixes>",
        combine_1 = "Combine three Enchantment Stones.",
        combine_2 = "1 percent chance for a supreme Enchantment Stone.",
        convert_button = "Convert",
        convert_header = "<Enchantment Stone Conversion>",
        convert_material = "Materials: Enchantment Stone + %s Crystal Figures",
        convert_chance = "Reroll an Enchantment Stone; %s%% chance for a rare affix.",
        convert_rare = "%s%% chance for an extremely rare affix.",
        craftable_affixes = "Craftable affixes",
        equipment_arrow = "Gear ==>",
        materials = "Materials",
        star_chance = "Starred gear\nboosts the chance",
        upgrade_button = "Enhance",
        star_up_button = "Upgrade star",
        repair_button = "Repair",
        name_label = "Name:",
        bind_label = "Bound to:",
        star_label = "Stars:",
        star_probability = "Star chance:",
        star_materials = "Star materials:",
        repair_materials = "Repair materials:",
        draw = "Draw", inherit = "Inherit", enhance = "Enhance",
        selective_clear = "<Select affixes to remove>",
        clear_help = "Choose the affixes you want to remove.",
        clear_cost = "Cost: Cleansing Tokens (see Gems tab)",
        clear_quantity = "One token per selected affix.",
        clear = "Remove",
    },
    equip_ui = {
        move_confirm = "Move all gear into the container?",
        dismantle_confirm = "Dismantle the gear?",
        reroll_confirm = "Reroll all affix values?",
        enchant_confirm = "Enchant the gear?",
        clear_confirm = "Remove one random affix?",
        empty = "Empty",
        socket_confirm = "Socket this gem?",
        punch_confirm = "Add a gem socket to this gear?",
        remove_gem_confirm = "Destroy one random socketed gem?",
        use_item = "Use %s",
        title = "Equipment Forge", put_in = "Add all", dismantle = "Dismantle all",
        equip = "↑\nGear", enchant_item = "↑\nEnchant",
        cleansing_item = "↑\nCleanse",
        upgrade = "Upgrade", enchant = "Enchant", clear = "Remove",
        enchant_hint = "[Stone / Scroll]\nAdd a random or selected affix",
        reroll_hint = "[Reset Gem]\nReroll affix values",
        clear_hint = "[Cleansing Stone]\nRemove one random affix",
        gem_title = "Socket Gems",
        inventory_hint = "↓ Your items ↓",
        equipment_hint = "Equipment →", gem = "Gem",
        confirm = "Confirm", cancel = "Cancel",
    },
    items = {
        a_punchStone = "Socket Stone",
        a_stoneDecoder = "Gem Remover",
        a_refreshStone = "Reset Gem",
        durableGem = "Durability Gem",
        damageBoostGem = "Damage Gem",
        powerMettleStone = "Power Stone",
        strideBead = "Speed Bead",
        shadowNightBead = "Nightfall Bead",
        followCritical = "Follower Critical Gem",
        followDamage = "Follower Damage Gem",
        followArmor = "Follower Defense Gem",
        twilightBead = "Dusk Bead",
        dayShineBead = "Daylight Bead",
        critStrikeStone = "Critical Stone",
        resistDamageGem = "Defense Stone",
        vigorousStone = "Vigor Stone",
        frostGuardCrystal = "Frostguard Crystal",
        heatGuardCrystal = "Heatguard Crystal",
        elementBead = "Elemental Star",
        retaliateGem = "Thorns Gem",
        spiderVengeance = "Spider Strike Gem",
        insectStrikeCrystal = "Insect Strike Crystal",
        shadowStrikeLuminary = "Shadow Strike Gem",
        bossStrikeGem = "Boss Strike Gem",
        z_clean_stone = "Cleansing Token",
        eightPigGem = "Yin Yin Stone",
        nkGem = "Jiaxin Candy",
        baconOmeletteBlessArmor = "Ultimate Defense Gem",
        baconOmeletteBlessAtk = "Ultimate Attack Gem",
        baconOmeletteBlessCritical = "Ultimate Critical Gem",
        baconOmeletteTrueDamage = "True Damage Gem",
        fxGem = "Effect Gem",
        treasure_atk = "Treasure Attack Gem",
        treasure_bj = "Treasure Critical Gem",
        treasure_armor = "Treasure Durability Gem",
        z_fertilizer = "Spell: Fertilize",
        z_plant = "Spell: Grow",
        z_soil = "Spell: Till Soil",
        z_rain = "Spell: Rain",
        z_sleep = "Spell: Sleep",
        z_stone = "Spell: Petrify",
    },
    mod_help = {
        "#Gameplay:orange:30",
        "#1. Creatures may spawn with random affixes; their maximum health rises over time.:white:25",
        "#2. Defeating enhanced creatures may drop equipment with special affixes.:white:25",
        "#3. Dismantling affixed equipment has a 10% chance to yield an affix stone (guaranteed with 3+ affixes).:white:25",
        "#4. Elite and boss creatures may drop equipment bundles or rare affix stones.:white:25",
        "#5. Defeating creatures may grant :white:25@effect_tally::25:25# or :white:25@remove_stone::25:25",
        "#6. Defeating creatures may grant special gems (see the forge's Gem tab).:white:25",
        "#7. Craft :white:25@suit_build::25:25# to inherit affixes and remove selected affixes.:white:25",
        "#8. Upgrade in :white:25@suit_build::25:25# to reroll affix values using a reset gem.:white:25",
        "# :white:50",

        "#Items:orange:30",
        "@effect_tally::25:25# Randomly enchants one piece of equipment at the forge.:white:25",
        "@remove_stone::25:25# Removes a random equipment affix at the forge.:white:25",
        "@essence::25:25# General crafting material.:white:25",
        "@cat_box::25:25# Portable enchantment box; converts affix stones into essence.:white:25",
        "@duck_box::25:25# Portable Pig King container.:white:25",
        "@staff_dis::25:25# Dismantles equipment or converts affix stones into essence.:white:25",
        "@ice_knife::25:25# Attacks can send out three waves of area fire damage.:white:25",
        "@staff_star::25:25# Ranged weapon with three projectiles.:white:25",
        "@treasure_tally::25:25# Reveals treasure locations.:white:25",
        "@treasure_build::25:25# Treasure site with encounters and enhanced creatures.:white:25",
        "@egg_nest::25:25# Egg incubator and display stand.:white:25",
        "#Common eggs - normal creatures.:white:25@egg_common::25:25",
        "#Precious eggs - elite creatures.:white:25@egg_silver::25:25",
        "#Rare eggs - bosses.:white:25@egg_gold::25:25",
        "#Starry eggs - treasure.:white:25@egg_starry_sky::25:25",
        "#Black eggs - extraordinary luck.:white:25@egg_black::25:25",
        "@hat_star::25:25# Upgradeable crown, sometimes found through hatching.:white:25",
        "# :white:50",

        "#Creature difficulty:orange:30",
        "#Easy - 1 starting affix; limits 2 / 3 / 4 (normal / elite / boss).:white:25",
        "#Every 20 days - +1 affix, with health scaling capped at day 100.:white:25",
        "#Normal - 2 starting affixes; limits 3 / 5 / 7.:white:25",
        "#Every 15 days - +1 affix, with health scaling capped at day 150.:white:25",
        "#Hard - 3 starting affixes; limits 5 / 7 / 10.:white:25",
        "#Every 12 days - +1 affix, with health scaling capped at day 200.:white:25",
        "# :white:50",

        "#Dismantling staff:yellow:30",
        "@staff_dis::25:25# Affix stone - enchant equipment.:white:25",
        "@staff_dis::25:25# Cleansing stone - remove an affix.:white:25",
        "@staff_dis::25:25# These shortcuts do not consume materials in the container:yellow:25",
        "@staff_dis::25:25# Gear - remove a gem.:white:25",
        "@staff_dis::25:25# Beefalo horn - punch a socket (uses a socket stone).:white:25",
        "@staff_dis::25:25# Green gem - reroll affix values (uses a reset gem).:white:25",
        "@staff_dis::25:25# Walrus tusk - add a speed gem.:white:25",
        "@staff_dis::25:25# Red gem - add a critical-hit gem.:white:25",
        "@staff_dis::25:25# Volt goat horn - add a boss-damage gem.:white:25",
        "@staff_dis::25:25# Spider silk - add a spider-damage gem.:white:25",
        "@staff_dis::25:25# Stinger - add an insect-damage gem.:white:25",
        "@staff_dis::25:25# Sand stone - add a damage-percent gem.:white:25",
        "@staff_dis::25:25# Steel wool - add a flat-damage gem.:white:25",
        "@staff_dis::25:25# Dragon scales / rhino horn / deerclops eye - treasure-grade gems.:white:25",
        "# :white:50",

        "#Special gems:orange:30",
        "@effect_gem::25:25# Socket stone - adds a gem socket to equipment.:white:25",
        "@effect_gem::25:25# Reset gem - rerolls existing affix values.:white:25",
        "@effect_gem::25:25# Gem remover - destroys one embedded gem at random.:white:25",
        "@effect_gem::25:25# Cleansing token - removes selected affixes at the forge.:white:25",
        "@effect_gem::25:25# Durability gem - restores 1 durability every 2 seconds.:white:25",
        "@effect_gem::25:25# Damage gem - +10 damage.:white:25",
        "@effect_gem::25:25# Power gem - +3% damage.:white:25",
        "@effect_gem::25:25# Speed gem - +3% movement speed.:white:25",
        "@effect_gem::25:25# Night / dusk / day gems - bonus damage at the matching time.:white:25",
        "@effect_gem::25:25# Critical gem - +3% critical chance and +10% critical effect.:white:25",
        "@effect_gem::25:25# Defense / thorns gems - reduce incoming damage or reflect damage.:white:25",
        "@effect_gem::25:25# Species gems - bonus damage against spiders, insects, shadows or bosses.:white:25",
        "@effect_gem::25:25# Follower gems - improve follower damage, defense or critical chance.:white:25",
        "@effect_gem::25:25# Treasure gems - powerful attack, critical or durability effects.:orange:25",
        "# :white:50",

        "#Compatibility:orange:30",
        "#Some multi-slot equipment mods can apply amulet or armor effects to the wrong slot.:white:25",
        "#This can produce incorrect health or damage values.:white:25",
        "#Try Extra Equip Slots (Modified), Workshop ID 2075943614.:white:25",
    },
    help_ui = {
        original_guide = "Original mod guide on Bilibili (by the original author)",
        changelog_title = "Starforge release notes",
        changelog_desc = "For Starforge changes, see github.com/VHcat/dst-starforge/releases. The original mod's historical notes are available in Chinese.",
        open_hint = "Mod help\nRight-click and drag to move",
        open_label = "Help",
        undefined_title = "Untitled",
        undefined_affix = "Unknown affix",
        undefined_desc = "No description",
        empty = "Empty",
        removed_set = "Set (removed):",
        effect = "Effect:",
        probability = "Drop rates",
        log_ps = "Note: showing up to the latest 100 world log entries",
    },
    log = {
        type_all = "All",
        type_stone = "Enchanting",
        type_treasure = "Treasure",
        type_egg = "Eggs",
    },
    ui = {
        action_use = "Use",
        action_treasure = "Search for treasure",
        container_dismantle = "Dismantle",
        container_convert = "Convert",
        container_gold = "Convert to gold",
        container_stone = "Convert to sand stone",
        rename_placeholder = "Name",
        help_tab_intro = "About the mod",
        help_tab_changes = "Update notes",
        help_tab_effects = "Affix details",
        help_tab_gems = "Gems / Items",
        help_tab_logs = "Log",
        help_title_intro = "About Starforge",
        help_title_changes = "Update notes",
        help_title_effects = "Affix effects",
        help_title_gems = "Gems / Items",
        help_title_logs = "World log",
        open_forge_hint = "Open forge (hotkey: %s)\nRight-click and drag to move",
        open_forge_label = "Forge",
    },
}
